import {
  listaSdk,
  erc20,
  erc4626,
  listaCli,
  parseUnits,
  formatUnits,
  type ToolError,
  type StepResult,
} from './runtime.ts';

// lista-lending-onchainos — Onchain OS DApp Skill
// Generated by dapp-connect-agenticwallet v1.8 (v0.3.0 full feature-parity re-conversion).
// Strictly follows the Onchain OS Skill specification.
//
// v0.3.0 — full 12-tool surface restored, v1.8 scaffold structure.
// Preserves the proven v0.1.6 business logic (live-validated on BSC mainnet
// 2026-05-11). FILL-IN.md and QA-PIPELINE.md added per v1.5+ template emission.
//
// ── Design decisions (v0.1.3) ───────────────────────────────────────────────
//
// Upstream `lista-lending` has 12 commands. This skill exposes 11:
//   - 6 transaction tools (build*) — wrap pending_sign with stateful single-step
//     emission for multi-step flows (allowance + action)
//   - 5 read-only tools (list*/get*/simulate*) — pure read; no signing
//
// Three upstream commands are intentionally NOT exposed:
//   - `version`  → metadata; onchainos has its own version surface
//   - `config`   → RPC override; onchainos uses its own RPC selection
//   - `select`   → persistent vault/market context. v0.1.3 chooses
//                  "explicit params per call" over "selected-context fallback"
//                  to keep tools stateless. Re-add as a state-mutation tool
//                  if user feedback shows the explicit-param model is too verbose.
//
// Error returns use a `{status:'error', error_code, message, suggestion?}`
// shape (forward-compat with the proposed scaffold spec change — see
// ~/Documents/dapp-scaffold-work/scaffold-improvements.md item P0-4).
//
// Multi-step pattern: every transaction tool that needs an ERC-20 approve
// (buildSupply, buildDeposit, buildRepay) follows the same stateful
// emission flow — re-read allowance on each call, return the approve
// pending_sign if insufficient, return the action pending_sign if ready.
// Borrow / withdraw / market-withdraw don't need user-side approval and
// emit a single pending_sign.
// ────────────────────────────────────────────────────────────────────────────
//
// ⚠️ RUNTIME MODEL — read carefully
// This file is NOT executed by Node/Deno/Bun or any runtime process. Claude Code Skill = Markdown instruction set.
// Execution flow: LLM reads this file → "simulates" the function body during inference (using Bash/WebFetch to call real APIs)
// → assembles return JSON per pending_sign contract → routes to Onchain OS via next_action.tool.
// Therefore: keep functions as "pure functional calldata construction"; avoid loops / subscriptions / long-running flows.
//
// DApp developers only need to fill in business logic at the TODO [third-party] comments.
// Importing ethers.Wallet / signTransaction / sendTransaction / local private keys is forbidden.

type PendingSign = {
  status: 'pending_sign';
  unsigned_tx: {
    to: string;
    data: string;
    value: string;
    chain: string;
  };
  description: string;
  next_action: { tool: string; reason?: string };
};

// ── EIP-712 Precision Helper — REQUIRED for all uint*/int* fields ────────────
// JS Number silently loses precision above 2^53-1 (uint64 and above).
// Using a plain Number for these fields causes on-chain signature verification
// failures with no client-side error — extremely hard to debug.
//
// Usage:  toSafeInt(apiResponse.sigDeadline)   // returns string, safe for all uint sizes
//
// ❌ Wrong:  message: { amount: apiResp.amount }
// ✅ Right:  message: { amount: toSafeInt(apiResp.amount) }
// ─────────────────────────────────────────────────────────────────────────────
function toSafeInt(v: unknown): string {
  if (v === null || v === undefined) {
    throw new Error('[EIP712-PRECISION] field is null/undefined — check API response');
  }
  return BigInt(String(v)).toString();
}

// ── Chain resolver — eliminates the silent-wrong-chain footgun ───────────────
// [ADDED v0.1.4] The earlier `chain === 'ethereum' ? 1 : 56` pattern silently
// defaulted any unrecognized chain name (typos, alternate spellings, unsupported
// chains) to BSC, which could route transactions to the wrong chain. This
// resolver returns either the resolved chain info or a structured ToolError so
// each wrapper can return the error to the agent instead of misrouting.
const CHAINS: Record<string, { id: number; caip2: string }> = {
  bsc:      { id: 56, caip2: 'eip155:56' },
  ethereum: { id: 1,  caip2: 'eip155:1'  },
};
function resolveChain(name: string | undefined): { name: string; id: number; caip2: string } | ToolError {
  const normalized = (name ?? 'bsc').toLowerCase();
  const entry = CHAINS[normalized];
  if (!entry) {
    return {
      status: 'error',
      error_code: 'UNSUPPORTED_CHAIN',
      message: `Chain '${name}' is not supported by this skill.`,
      suggestion: `Use one of: ${Object.keys(CHAINS).join(', ')}.`,
    };
  }
  return { name: normalized, ...entry };
}

// ── Amount validator — catches the amount=0 / negative / malformed footgun ───
// [ADDED v0.1.4] parseUnits accepts '0' silently (returns 0n) which then passes
// downstream gates and reaches the SDK, where it builds a no-op tx or fails
// with an unclear SDK error. Validate up front and return a clean ToolError.
function validatePositiveAmount(amount: string | undefined, fieldName = 'amount'): ToolError | null {
  if (amount === undefined || amount === null || amount === '') {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (!/^\d+(\.\d+)?$/.test(amount)) {
    return { status: 'error', error_code: 'INVALID_PARAM', message: `\`${fieldName}\` must be a non-negative decimal string (got '${amount}').` };
  }
  if (Number(amount) === 0) {
    return { status: 'error', error_code: 'INVALID_PARAM', message: `\`${fieldName}\` must be greater than zero.` };
  }
  return null;
}

// ── Address / market-id validators ───────────────────────────────────────────
// [ADDED v0.1.4 — round 2] Catches malformed IDs at the tool entry so the
// underlying SDK never sees a garbage value. Without these, SDK errors
// surface as raw stack traces instead of structured ToolError.
function validateEvmAddress(addr: string | undefined, fieldName: string): ToolError | null {
  if (!addr) {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (!/^0x[a-fA-F0-9]{40}$/.test(addr)) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be a 0x-prefixed 40-char hex EVM address (got '${addr}').`,
    };
  }
  return null;
}

function validateMarketId(id: string | undefined, fieldName = 'marketId'): ToolError | null {
  if (!id) {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (!/^0x[a-fA-F0-9]{64}$/.test(id)) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be a 0x-prefixed 64-char hex market id (got '${id}').`,
    };
  }
  return null;
}

// ── SDK-call wrapper — catches runtime errors and surfaces as ToolError ──────
// [ADDED v0.1.4 — round 2] Wraps any SDK / RPC call. If the underlying call
// throws (invalid target, network error, etc.), returns a structured ToolError
// instead of letting the exception propagate to the CLI as an unhelpful stack.
async function safeSdkCall<T>(
  fn: () => Promise<T>,
  errorCode: string,
  context: string,
): Promise<T | ToolError> {
  try {
    return await fn();
  } catch (e) {
    return {
      status: 'error',
      error_code: errorCode,
      message: `${context}: ${(e as Error).message}`,
    };
  }
}

// ============================================================================
// TRANSACTION TOOLS (wrapped in pending_sign → routed to onchainos wallet contract-call)
// ============================================================================

// ───── buildDeposit — Vault deposit (contract-call) ─────
//
// [FILLED v0.1.3] Vault deposit. The vault holds the asset on the user's
// behalf and the user must approve the vault contract to pull funds.
// Uses the stateful single-step emission pattern (allowance check → emit
// approve or deposit). Mirrors buildSupply's structure for market collateral.
//
// Required params: { vaultAddress, amount, walletAddress }
// Optional params: { chain }  // 'bsc' (default) or 'ethereum'
async function buildDeposit(params: {
  vaultAddress: string;
  amount: string;
  walletAddress: string;
  chain?: string;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, id: chainId } = chainResult;
  const { vaultAddress, amount, walletAddress } = params;
  const validationError =
    validateEvmAddress(vaultAddress, 'vaultAddress') ??
    validateEvmAddress(walletAddress, 'walletAddress') ??
    validatePositiveAmount(amount);
  if (validationError) return validationError;

  // Step A — read vault config (asset token address, symbol, decimals).
  //   Runtime: listaSdk.getVaultInfo(chainId, vaultAddress)
  const vaultInfo = await safeSdkCall(
    () => listaSdk.getVaultInfo(chainId, vaultAddress),
    'UNKNOWN_VAULT',
    `vault ${vaultAddress} on ${chain}`,
  );
  if ('status' in vaultInfo) return vaultInfo;
  const assetToken: string = vaultInfo.assetInfo.address;
  const assetSymbol: string = vaultInfo.assetInfo.symbol;
  const assetDecimals: number = vaultInfo.assetInfo.decimals;

  // Step B — parse user-friendly amount to bigint wei.
  const assets = parseUnits(amount, assetDecimals);

  // Step C — allowance check (read-only).
  //   ERC-4626-style vaults pull funds; user must approve the vault contract itself.
  const allowanceResult = await safeSdkCall(
    () => erc20.allowance(assetToken, walletAddress, vaultAddress, chainId),
    'RPC_ERROR',
    `reading ERC-20 allowance for ${assetToken}`,
  );
  if (typeof allowanceResult === 'object' && allowanceResult !== null && 'status' in allowanceResult) return allowanceResult;
  const currentAllowance: bigint = allowanceResult as bigint;

  // ── Branch: insufficient allowance → emit Step 1 of 2 (approve) ──
  if (currentAllowance < assets) {
    const approveData =
      '0x095ea7b3' +
      vaultAddress.toLowerCase().replace(/^0x/, '').padStart(64, '0') +
      assets.toString(16).padStart(64, '0');

    return {
      status: 'pending_sign',
      unsigned_tx: {
        to: assetToken,
        data: approveData,
        value: '0',
        chain,
      },
      description:
        `Step 1 of 2: Approve ${amount} ${assetSymbol} for Lista vault ${vaultAddress}. ` +
        `After this transaction lands, re-invoke buildDeposit with the same params to receive ` +
        `the deposit transaction.`,
      next_action: { tool: 'onchainos wallet contract-call' },
    };
  }

  // ── Branch: allowance sufficient → emit deposit step ──
  //   Runtime: listaSdk.buildDepositParams({chainId, vaultAddress, walletAddress, assets})
  //   ERC-4626-style: encodes deposit(assets, receiver=walletAddress) on the vault.
  const steps = await safeSdkCall(
    () => listaSdk.buildDepositParams({ chainId, vaultAddress, walletAddress, assets }),
    'SDK_ERROR',
    `building deposit calldata for vault ${vaultAddress}`,
  );
  if ('status' in steps) return steps;
  const depositStep = steps.find((s) => s.step === 'deposit') ?? steps[steps.length - 1];

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: depositStep.params.to,
      data: depositStep.params.data,
      value: depositStep.params.value ? depositStep.params.value.toString() : '0',
      chain,
    },
    description: `Deposit ${amount} ${assetSymbol} into Lista vault ${vaultAddress}.`,
    next_action: { tool: 'onchainos wallet contract-call' },
  };
}

// ───── buildWithdraw — Vault withdraw (contract-call) ─────
//
// [FILLED v0.1.3] Vault withdraw. User is the share owner, calling
// withdraw/redeem on the vault directly — no ERC-20 approve needed.
// Single-step. Supports `withdrawAll: true` for full-balance redemption.
//
// Required params: { vaultAddress, walletAddress } + ONE of { amount } or { withdrawAll: true }
// Optional params: { chain }  // 'bsc' (default) or 'ethereum'
async function buildWithdraw(params: {
  vaultAddress: string;
  walletAddress: string;
  amount?: string;
  withdrawAll?: boolean;
  chain?: string;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, id: chainId } = chainResult;
  const { vaultAddress, walletAddress, amount, withdrawAll } = params;
  const targetError =
    validateEvmAddress(vaultAddress, 'vaultAddress') ??
    validateEvmAddress(walletAddress, 'walletAddress');
  if (targetError) return targetError;

  if (!amount && !withdrawAll) {
    return {
      status: 'error',
      error_code: 'MISSING_AMOUNT',
      message: 'Either `amount` or `withdrawAll: true` must be provided.',
      suggestion: 'Pass amount as a UI-units string, OR set withdrawAll: true to redeem all shares.',
    };
  }
  if (amount && withdrawAll) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: 'Cannot pass both `amount` and `withdrawAll: true` — they are mutually exclusive.',
      suggestion: 'Drop one. Use withdrawAll for full balance, or amount for a partial withdraw.',
    };
  }
  if (amount) {
    const amountError = validatePositiveAmount(amount);
    if (amountError) return amountError;
  }

  // Step A — read vault config.
  const vaultInfo = await safeSdkCall(
    () => listaSdk.getVaultInfo(chainId, vaultAddress),
    'UNKNOWN_VAULT',
    `vault ${vaultAddress} on ${chain}`,
  );
  if ('status' in vaultInfo) return vaultInfo;
  const assetSymbol: string = vaultInfo.assetInfo.symbol;
  const assetDecimals: number = vaultInfo.assetInfo.decimals;

  // Step B — read user position (needed for withdrawAll, also validates user has shares).
  const userData = await safeSdkCall(
    () => listaSdk.getVaultUserData(chainId, vaultAddress, walletAddress, vaultInfo),
    'RPC_ERROR',
    `reading vault user data for ${walletAddress}`,
  );
  if ('status' in userData) return userData;

  if (userData.shares === 0n) {
    return {
      status: 'error',
      error_code: 'NO_VAULT_POSITION',
      message: `No shares held in vault ${vaultAddress}.`,
    };
  }

  // Step C — determine effective withdraw amount.
  let buildArgs: { chainId: number; vaultAddress: string; walletAddress: string; assets?: bigint; shares?: bigint };
  let displayAmount: string;

  if (withdrawAll) {
    // Use shares directly (ERC-4626 redeem) — avoids the assets→shares precision loss
    // that can occur if the vault has accumulated yield since the last block.
    buildArgs = { chainId, vaultAddress, walletAddress, shares: userData.shares };
    // [v0.1.6] SDK's userData.assets returns 0 even when shares > 0. Read
    // convertToAssets directly from the vault for an accurate display value.
    const underlying = await erc4626.convertToAssets(vaultAddress, userData.shares, chainId);
    displayAmount =
      `${formatUnits(underlying, assetDecimals)} ${assetSymbol} ` +
      `(all ${formatUnits(userData.shares, assetDecimals)} shares)`;
  } else {
    const assets = parseUnits(amount!, assetDecimals);
    if (assets > userData.assets) {
      return {
        status: 'error',
        error_code: 'EXCEEDS_BALANCE',
        message: `Withdraw ${amount} ${assetSymbol} exceeds current vault balance (${formatUnits(userData.assets, assetDecimals)} ${assetSymbol}).`,
        suggestion: `Use amount up to ${formatUnits(userData.assets, assetDecimals)}, or set withdrawAll: true.`,
      };
    }
    buildArgs = { chainId, vaultAddress, walletAddress, assets };
    displayAmount = `${amount} ${assetSymbol}`;
  }

  // Step D — build withdraw/redeem calldata.
  //   Runtime: listaSdk.buildWithdrawParams(buildArgs) — single-step (no approve).
  const steps = await safeSdkCall(
    () => listaSdk.buildWithdrawParams(buildArgs),
    'SDK_ERROR',
    `building withdraw calldata for vault ${vaultAddress}`,
  );
  if ('status' in steps) return steps;
  const withdrawStep = steps.find((s) => s.step === 'withdraw' || s.step === 'redeem') ?? steps[steps.length - 1];

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: withdrawStep.params.to,
      data: withdrawStep.params.data,
      value: withdrawStep.params.value ? withdrawStep.params.value.toString() : '0',
      chain,
    },
    description: `Withdraw ${displayAmount} from Lista vault ${vaultAddress}.`,
    next_action: { tool: 'onchainos wallet contract-call' },
  };
}

// ───── buildSupply — Market supply collateral (contract-call) ─────
//
// [FILLED v0.1.3] Multi-step strategy: stateful single-step emission.
// Each invocation returns ONE pending_sign — either an approve step or
// the supply step, depending on current ERC-20 allowance. The agent
// signs+broadcasts the returned step via Onchain OS, then re-invokes
// buildSupply. On the second call, allowance is now sufficient, so the
// function returns the supply step. No state is kept between calls;
// every call re-reads on-chain state.
//
// Required params: { marketId, amount, walletAddress }
// Optional params: { chain }  // 'bsc' (default, eip155:56) or 'ethereum' (eip155:1)
async function buildSupply(params: {
  marketId: string;
  amount: string;
  walletAddress: string;
  chain?: string;
}): Promise<PendingSign> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, id: chainId } = chainResult;
  const { marketId, amount, walletAddress } = params;
  const validationError =
    validateMarketId(marketId) ??
    validateEvmAddress(walletAddress, 'walletAddress') ??
    validatePositiveAmount(amount);
  if (validationError) return validationError;

  // TODO [third-party] Step A — read market write config (collateral token + market contract address).
  //   Runtime hint for the LLM (translate to Bash):
  //     node ~/.claude/skills/lista-lending/dist/cli/cli.bundle.mjs markets \
  //       --chain eip155:${chainId} \
  //     then locate marketId in the JSON; collateralInfo.{address,symbol,decimals}
  //     and the market contract address are all in the response.
  //   Equivalent SDK call (if invoked from a Node one-liner):
  //     const sdk = require('~/.claude/skills/lista-lending/dist/sdk.js').getSDK();
  //     const marketInfo = await sdk.getWriteConfig(${chainId}, '${marketId}');
  const marketInfo = await safeSdkCall(
    () => listaSdk.getWriteConfig(chainId, marketId),
    'UNKNOWN_MARKET',
    `market ${marketId} on ${chain}`,
  );
  if ('status' in marketInfo) return marketInfo;
  const collateralToken: string = marketInfo.collateralInfo.address;
  const collateralSymbol: string = marketInfo.collateralInfo.symbol;
  const collateralDecimals: number = marketInfo.collateralInfo.decimals;
  const marketContract: string = marketInfo.marketContract;

  // TODO [third-party] Step B — parse the user-friendly amount string to bigint wei.
  //   Mirrors ~/.claude/skills/lista-lending/src/utils/validators.ts: parsePositiveUnits.
  //   Reject non-positive values and trailing decimals beyond collateralDecimals.
  const assets: bigint = parseUnits(amount, collateralDecimals);

  // TODO [third-party] Step C — read current ERC-20 allowance (READ-ONLY, no signing).
  //   Runtime hint: encode allowance(address,address) and call via JSON-RPC.
  const allowanceResult = await safeSdkCall(
    () => erc20.allowance(collateralToken, walletAddress, marketContract, chainId),
    'RPC_ERROR',
    `reading ERC-20 allowance for ${collateralToken}`,
  );
  if (typeof allowanceResult === 'object' && allowanceResult !== null && 'status' in allowanceResult) return allowanceResult;
  const currentAllowance: bigint = allowanceResult as bigint;

  // ── Branch: insufficient allowance → emit Step 1 of 2 (approve) ─────────────
  if (currentAllowance < assets) {
    // ERC-20 approve(spender, amount) calldata:
    //   selector 0x095ea7b3 + pad32(spender) + pad32(amount)
    const approveData =
      '0x095ea7b3' +
      marketContract.toLowerCase().replace(/^0x/, '').padStart(64, '0') +
      assets.toString(16).padStart(64, '0');

    return {
      status: 'pending_sign',
      unsigned_tx: {
        to: collateralToken,
        data: approveData,
        value: '0',
        chain,
      },
      description:
        `Step 1 of 2: Approve ${amount} ${collateralSymbol} for Lista Lending market ${marketId} ` +
        `(spender ${marketContract}). After this transaction lands, re-invoke buildSupply with the ` +
        `same params to receive the supply transaction.`,
      next_action: { tool: 'onchainos wallet contract-call' },
    };
  }

  // ── Branch: allowance sufficient → emit supply step ─────────────────────────
  //
  // TODO [third-party] Step D — call Lista SDK to build the supply step.
  //   Runtime hint: use the SDK directly to avoid re-doing approve detection.
  //     const steps = await listaSdk.buildSupplyParams({
  //       chainId, marketId, walletAddress, assets,
  //     });
  //   Lista's SDK returns steps[]: [{step: 'approve', params: {...}}, {step: 'supply', params: {to,data,value}}]
  //   when allowance is insufficient, or [{step: 'supply', ...}] when sufficient. Since we already
  //   gated on allowance above, the supply step is the last (and usually only) element.
  const steps = await safeSdkCall(
    () => listaSdk.buildSupplyParams({ chainId, marketId, walletAddress, assets }),
    'SDK_ERROR',
    `building supply calldata for market ${marketId}`,
  );
  if ('status' in steps) return steps;
  const supplyStep = steps.find((s) => s.step === 'supply') ?? steps[steps.length - 1];

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: supplyStep.params.to,
      data: supplyStep.params.data,
      value: supplyStep.params.value ? supplyStep.params.value.toString() : '0',
      chain,
    },
    description:
      `Supply ${amount} ${collateralSymbol} as collateral to Lista Lending market ${marketId}.`,
    next_action: { tool: 'onchainos wallet contract-call' },
  };
}

// ── Runtime imports (v0.1.4+: real execution via runtime.ts) ──────────────────
// Earlier versions of this file used ambient `declare` blocks here — the tool
// functions referenced runtime helpers (listaSdk, erc20, listaCli, parseUnits,
// formatUnits) that the LLM was expected to translate to Bash/RPC at inference
// time. v0.1.4 moves to real execution: runtime.ts provides actual mock (or
// later, live) implementations and the tool functions just call them.
//
// To switch between mock and live implementations, swap the bodies in runtime.ts —
// the index.ts call sites stay unchanged.
//
// Re-export the helpers as type-erased names so the rest of the file reads
// identically to the pre-import version.

// ───── buildBorrow — Market borrow (contract-call) ─────
//
// [FIXED + FILLED v0.1.3] Earlier draft aliased `buildBorrowSimulationPayload`
// (a DRY-RUN reporter) into this slot — that was wrong. The real calldata
// builder is `sdk.buildBorrowParams`. The simulation function moved to
// `simulateBorrow` (read-only). This wrapper is single-step: borrow only
// transfers loan tokens OUT of the market to the user — no ERC-20 approve
// from the user is required.
//
// Required params: { marketId, amount, walletAddress }
// Optional params: { chain }  // 'bsc' (default) or 'ethereum'
async function buildBorrow(params: {
  marketId: string;
  amount: string;
  walletAddress: string;
  chain?: string;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, id: chainId } = chainResult;
  const { marketId, amount, walletAddress } = params;
  const validationError =
    validateMarketId(marketId) ??
    validateEvmAddress(walletAddress, 'walletAddress') ??
    validatePositiveAmount(amount);
  if (validationError) return validationError;

  // Step A — read market write config (loan token + market contract).
  const marketInfo = await safeSdkCall(
    () => listaSdk.getWriteConfig(chainId, marketId),
    'UNKNOWN_MARKET',
    `market ${marketId} on ${chain}`,
  );
  if ('status' in marketInfo) return marketInfo;
  if (!marketInfo.loanInfo) {
    return { status: 'error', error_code: 'INVALID_MARKET', message: `Market ${marketId} has no loan asset configured.` };
  }
  const loanSymbol = marketInfo.loanInfo.symbol;
  const loanDecimals = marketInfo.loanInfo.decimals;

  // Step B — read user position to derive borrowable capacity.
  //   Runtime: listaSdk.getMarketUserData(chainId, marketId, walletAddress)
  //   Returns: { loanable: bigint, borrowed: bigint, decimals: {c, l}, ... }
  const userData = await safeSdkCall(
    () => listaSdk.getMarketUserData(chainId, marketId, walletAddress),
    'RPC_ERROR',
    `reading market user data for ${walletAddress}`,
  );
  if ('status' in userData) return userData;

  // Step C — parse user amount to bigint wei.
  const assets = parseUnits(amount, loanDecimals);

  // Step D — capacity gate (mirrors Lista's executeBorrowTransaction check).
  if (userData.loanable < assets) {
    return {
      status: 'error',
      error_code: 'INSUFFICIENT_BORROW_CAPACITY',
      message:
        `Cannot borrow ${amount} ${loanSymbol}. ` +
        `Max borrowable: ${formatUnits(userData.loanable, loanDecimals)} ${loanSymbol}.`,
      suggestion: 'Supply more collateral via buildSupply, or reduce borrow amount.',
    };
  }

  // Step E — safe-cap gate (mirrors Lista's simulate.ts: currentLoanable * 0.95).
  //   Borrowing above 95% of loanable is technically permitted but flags liquidation risk.
  const safeCap = (userData.loanable * 95n) / 100n;
  if (assets > safeCap) {
    return {
      status: 'error',
      error_code: 'EXCEEDS_SAFE_BORROW_CAP',
      message:
        `Requested borrow ${amount} ${loanSymbol} exceeds 95% of loanable ` +
        `(${formatUnits(safeCap, loanDecimals)} ${loanSymbol}). Borrowing this much risks ` +
        `immediate liquidation if collateral price drops even slightly.`,
      suggestion: 'Stay at or below 95% of loanable, or supply more collateral first.',
    };
  }

  // Step F — build the borrow calldata.
  //   Runtime: listaSdk.buildBorrowParams({chainId, marketId, assets, walletAddress, marketInfo})
  //   Returns steps[]. Borrow is typically single-step.
  const steps = await safeSdkCall(
    () => listaSdk.buildBorrowParams({ chainId, marketId, assets, walletAddress, marketInfo }),
    'SDK_ERROR',
    `building borrow calldata for market ${marketId}`,
  );
  if ('status' in steps) return steps;
  const borrowStep = steps.find((s) => s.step === 'borrow') ?? steps[steps.length - 1];

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: borrowStep.params.to,
      data: borrowStep.params.data,
      value: borrowStep.params.value ? borrowStep.params.value.toString() : '0',
      chain,
    },
    description: `Borrow ${amount} ${loanSymbol} from Lista Lending market ${marketId}.`,
    next_action: { tool: 'onchainos wallet contract-call' },
  };
}

// ───── buildRepay — Market repay (contract-call) ─────
//
// [FIXED + FILLED v0.1.3] Earlier draft aliased `buildRepaySimulationPayload`
// (a DRY-RUN reporter) into this slot — that was wrong. The real calldata
// builder is `sdk.buildRepayParams`. The simulation function moved to
// `simulateRepay` (read-only). This wrapper is multi-step: repaying requires
// the user to first approve the loan token for the market contract, then
// repay. Uses the same stateful single-step emission pattern as buildSupply.
//
// Required params: { marketId, walletAddress } + ONE of { amount } or { repayAll: true }
// Optional params: { chain }  // 'bsc' (default) or 'ethereum'
async function buildRepay(params: {
  marketId: string;
  walletAddress: string;
  amount?: string;
  repayAll?: boolean;
  chain?: string;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, id: chainId } = chainResult;
  const { marketId, walletAddress, amount, repayAll } = params;
  const targetError =
    validateMarketId(marketId) ??
    validateEvmAddress(walletAddress, 'walletAddress');
  if (targetError) return targetError;

  // Validate exactly one of amount / repayAll is set.
  if (!amount && !repayAll) {
    return {
      status: 'error',
      error_code: 'MISSING_AMOUNT',
      message: 'Either `amount` or `repayAll: true` must be provided.',
      suggestion: 'Pass amount as a UI-units string, OR set repayAll: true to repay full debt.',
    };
  }
  if (amount && repayAll) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: 'Cannot pass both `amount` and `repayAll: true` — they are mutually exclusive.',
      suggestion: 'Drop one. Use repayAll for full debt, or amount for a partial repay.',
    };
  }
  if (amount) {
    const amountError = validatePositiveAmount(amount);
    if (amountError) return amountError;
  }

  // Step A — read market write config.
  const marketInfo = await safeSdkCall(
    () => listaSdk.getWriteConfig(chainId, marketId),
    'UNKNOWN_MARKET',
    `market ${marketId} on ${chain}`,
  );
  if ('status' in marketInfo) return marketInfo;
  if (!marketInfo.loanInfo) {
    return { status: 'error', error_code: 'INVALID_MARKET', message: `Market ${marketId} has no loan asset configured.` };
  }
  const loanToken = marketInfo.loanInfo.address;
  const loanSymbol = marketInfo.loanInfo.symbol;
  const loanDecimals = marketInfo.loanInfo.decimals;
  const marketContract = marketInfo.marketContract;

  // Step B — read user position to determine repay amount and validate debt exists.
  const userData = await safeSdkCall(
    () => listaSdk.getMarketUserData(chainId, marketId, walletAddress),
    'RPC_ERROR',
    `reading market user data for ${walletAddress}`,
  );
  if ('status' in userData) return userData;
  const currentDebt: bigint = userData.borrowed;

  if (currentDebt === 0n) {
    return {
      status: 'error',
      error_code: 'NO_DEBT_TO_REPAY',
      message: `No outstanding debt on market ${marketId}.`,
    };
  }

  // Step C — determine effective repay amount.
  let repayAmount: bigint;
  let displayAmount: string;
  if (repayAll) {
    repayAmount = currentDebt;
    displayAmount = `${formatUnits(currentDebt, loanDecimals)} ${loanSymbol} (full debt)`;
  } else {
    repayAmount = parseUnits(amount!, loanDecimals);
    if (repayAmount > currentDebt) {
      return {
        status: 'error',
        error_code: 'EXCEEDS_DEBT',
        message: `Repay ${amount} ${loanSymbol} exceeds current debt (${formatUnits(currentDebt, loanDecimals)} ${loanSymbol}).`,
        suggestion: `Use amount up to ${formatUnits(currentDebt, loanDecimals)}, or set repayAll: true.`,
      };
    }
    displayAmount = `${amount} ${loanSymbol}`;
  }

  // Step D — allowance check on loan token (user must approve market to pull funds).
  const repayAllowanceResult = await safeSdkCall(
    () => erc20.allowance(loanToken, walletAddress, marketContract, chainId),
    'RPC_ERROR',
    `reading ERC-20 allowance for ${loanToken}`,
  );
  if (typeof repayAllowanceResult === 'object' && repayAllowanceResult !== null && 'status' in repayAllowanceResult) return repayAllowanceResult;
  const currentAllowance: bigint = repayAllowanceResult as bigint;

  // ── Branch: insufficient allowance → emit Step 1 of 2 (approve loan token) ──
  if (currentAllowance < repayAmount) {
    const approveData =
      '0x095ea7b3' +
      marketContract.toLowerCase().replace(/^0x/, '').padStart(64, '0') +
      repayAmount.toString(16).padStart(64, '0');

    return {
      status: 'pending_sign',
      unsigned_tx: {
        to: loanToken,
        data: approveData,
        value: '0',
        chain,
      },
      description:
        `Step 1 of 2: Approve ${displayAmount} for repay to Lista Lending market ${marketId} ` +
        `(spender ${marketContract}). After this lands, re-invoke buildRepay with the same ` +
        `params to receive the repay transaction.`,
      next_action: { tool: 'onchainos wallet contract-call' },
    };
  }

  // ── Branch: allowance sufficient → emit repay step ──
  //   Runtime: listaSdk.buildRepayParams({chainId, marketId, assets?, repayAll, walletAddress, marketInfo, userData})
  //   When repayAll is set, assets must be undefined (the SDK reads it from userData).
  const steps = await safeSdkCall(
    () => listaSdk.buildRepayParams({
      chainId,
      marketId,
      assets: repayAll ? undefined : repayAmount,
      repayAll: Boolean(repayAll),
      walletAddress,
      marketInfo,
      userData,
    }),
    'SDK_ERROR',
    `building repay calldata for market ${marketId}`,
  );
  if ('status' in steps) return steps;
  const repayStep = steps.find((s) => s.step === 'repay') ?? steps[steps.length - 1];

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: repayStep.params.to,
      data: repayStep.params.data,
      value: repayStep.params.value ? repayStep.params.value.toString() : '0',
      chain,
    },
    description: `Repay ${displayAmount} debt on Lista Lending market ${marketId}.`,
    next_action: { tool: 'onchainos wallet contract-call' },
  };
}

// ───── buildMarketWithdraw — Market collateral withdraw (contract-call) ─────
//
// [FILLED v0.1.3] Withdraw supplied collateral from a market. User owns
// the collateral and calls withdrawCollateral directly on the market —
// no ERC-20 approve needed. Single-step. Supports `withdrawAll: true` only
// when user has zero outstanding debt (otherwise the market would be
// undercollateralized).
//
// Required params: { marketId, walletAddress } + ONE of { amount } or { withdrawAll: true }
// Optional params: { chain }  // 'bsc' (default) or 'ethereum'
async function buildMarketWithdraw(params: {
  marketId: string;
  walletAddress: string;
  amount?: string;
  withdrawAll?: boolean;
  chain?: string;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, id: chainId } = chainResult;
  const { marketId, walletAddress, amount, withdrawAll } = params;
  const targetError =
    validateMarketId(marketId) ??
    validateEvmAddress(walletAddress, 'walletAddress');
  if (targetError) return targetError;

  if (!amount && !withdrawAll) {
    return {
      status: 'error',
      error_code: 'MISSING_AMOUNT',
      message: 'Either `amount` or `withdrawAll: true` must be provided.',
      suggestion: 'Pass amount as a UI-units string, OR set withdrawAll: true to withdraw all collateral.',
    };
  }
  if (amount && withdrawAll) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: 'Cannot pass both `amount` and `withdrawAll: true` — they are mutually exclusive.',
      suggestion: 'Drop one. Use withdrawAll for full collateral, or amount for a partial withdraw.',
    };
  }
  if (amount) {
    const amountError = validatePositiveAmount(amount);
    if (amountError) return amountError;
  }

  // Step A — read market write config (collateral token + market contract).
  const marketInfo = await safeSdkCall(
    () => listaSdk.getWriteConfig(chainId, marketId),
    'UNKNOWN_MARKET',
    `market ${marketId} on ${chain}`,
  );
  if ('status' in marketInfo) return marketInfo;
  const collateralSymbol: string = marketInfo.collateralInfo.symbol;
  const collateralDecimals: number = marketInfo.collateralInfo.decimals;

  // Step B — read user position (collateral balance, outstanding debt, withdrawable cap).
  const userData = await safeSdkCall(
    () => listaSdk.getMarketUserData(chainId, marketId, walletAddress),
    'RPC_ERROR',
    `reading market user data for ${walletAddress}`,
  );
  if ('status' in userData) return userData;

  if (userData.collateral === 0n) {
    return {
      status: 'error',
      error_code: 'NO_COLLATERAL',
      message: `No collateral supplied on market ${marketId}.`,
    };
  }

  // Step C — determine effective withdraw amount + safety gates.
  let withdrawAmount: bigint;
  let displayAmount: string;

  if (withdrawAll) {
    if (userData.borrowed > 0n) {
      return {
        status: 'error',
        error_code: 'WITHDRAW_ALL_HAS_DEBT',
        message:
          `Cannot withdrawAll: ${formatUnits(userData.borrowed, marketInfo.loanInfo!.decimals)} ` +
          `${marketInfo.loanInfo!.symbol} debt still outstanding.`,
        suggestion: 'Repay all debt first via buildRepay { repayAll: true }, then retry withdrawAll.',
      };
    }
    withdrawAmount = userData.collateral;
    displayAmount = `${formatUnits(userData.collateral, collateralDecimals)} ${collateralSymbol} (all)`;
  } else {
    withdrawAmount = parseUnits(amount!, collateralDecimals);
    // withdrawable cap is min(collateral, what LLTV allows given current debt).
    if (withdrawAmount > userData.withdrawable) {
      return {
        status: 'error',
        error_code: 'EXCEEDS_WITHDRAWABLE',
        message:
          `Withdraw ${amount} ${collateralSymbol} exceeds withdrawable cap ` +
          `(${formatUnits(userData.withdrawable, collateralDecimals)} ${collateralSymbol}). ` +
          `Pulling more would push the position above LLTV.`,
        suggestion: `Use amount up to ${formatUnits(userData.withdrawable, collateralDecimals)}, or repay debt to free up more collateral.`,
      };
    }
    displayAmount = `${amount} ${collateralSymbol}`;
  }

  // Step D — build withdrawCollateral calldata.
  //   Runtime: listaSdk.buildMarketWithdrawParams({chainId, marketId, assets, walletAddress, marketInfo, userData})
  const steps = await safeSdkCall(
    () => listaSdk.buildMarketWithdrawParams({
      chainId,
      marketId,
      assets: withdrawAmount,
      walletAddress,
      marketInfo,
      userData,
    }),
    'SDK_ERROR',
    `building market-withdraw calldata for market ${marketId}`,
  );
  if ('status' in steps) return steps;
  const withdrawStep = steps.find((s) => s.step === 'withdraw' || s.step === 'withdrawCollateral') ?? steps[steps.length - 1];

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: withdrawStep.params.to,
      data: withdrawStep.params.data,
      value: withdrawStep.params.value ? withdrawStep.params.value.toString() : '0',
      chain,
    },
    description: `Withdraw ${displayAmount} collateral from Lista Lending market ${marketId}.`,
    next_action: { tool: 'onchainos wallet contract-call' },
  };
}

// ============================================================================
// READ-ONLY TOOLS (pass-through, no pending_sign)
// ============================================================================

// ───── listMarkets — List Lista Lending markets ─────
//
// [FILLED v0.1.3] Delegates to the source CLI. Filters out SmartLending
// (zone === 3) and fixed-term (termType === 1) markets per upstream behavior
// — those aren't supported by the write-side wrappers, so listing them would
// surface markets the user can't actually act on.
async function listMarkets(params: {
  chain?: string;
  page?: number;
  pageSize?: number;
  sort?: 'apy' | 'liquidity' | 'tvl' | string;
  order?: 'asc' | 'desc';
  loans?: string[];        // filter by loan-token symbols, e.g. ['USDT', 'USD1']
  collaterals?: string[];  // filter by collateral-token symbols
  keyword?: string;
}) {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, caip2: chainId } = chainResult;

  // Runtime hint for the LLM: invoke the source CLI and parse stdout JSON.
  //   node ~/.claude/skills/lista-lending/dist/cli/cli.bundle.mjs markets \
  //     --chain <chainId> [--sort <sort>] [--order <order>] [--page <page>] \
  //     [--page-size <pageSize>] [--loans <comma-list>] [--collaterals <comma-list>] \
  //     [--keyword <keyword>]
  // The CLI already applies the SmartLending/fixed-term filter (see
  // src/commands/markets.ts), so the returned list is safe to surface to the user.
  //
  // Always include this user-facing note when presenting the result:
  //   "Smart Lending and fixed-term market operations are currently not supported in this skill.
  //    For full functionality, please use the Lista website."
  const result = await listaCli.run('markets', {
    chain: chainId,
    sort: params.sort,
    order: params.order,
    page: params.page,
    pageSize: params.pageSize,
    loans: params.loans?.join(','),
    collaterals: params.collaterals?.join(','),
    keyword: params.keyword,
  });

  return {
    status: 'ok',
    chain,
    note: 'Smart Lending and fixed-term markets are filtered out.',
    data: result,  // pagination + market[] with collateral/loan/LLTV/borrowRate/liquidity
  };
}

// ───── listVaults — List Lista Lending vaults ─────
//
// [FILLED v0.1.3] Delegates to the source CLI; supports the same
// pagination/sort/filter param set as upstream.
async function listVaults(params: {
  chain?: string;
  page?: number;
  pageSize?: number;
  sort?: 'apy' | 'tvl' | string;
  order?: 'asc' | 'desc';
  assets?: string[];        // filter by asset addresses
  curators?: string[];      // filter by curator names
  zone?: number;
  keyword?: string;
}) {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, caip2: chainId } = chainResult;

  // Runtime hint:
  //   node ~/.claude/skills/lista-lending/dist/cli/cli.bundle.mjs vaults \
  //     --chain <chainId> [--sort <sort>] [--order <order>] [--page <page>] \
  //     [--page-size <pageSize>] [--assets <addrs>] [--curators <names>] \
  //     [--zone <zone>] [--keyword <keyword>]
  const result = await listaCli.run('vaults', {
    chain: chainId,
    sort: params.sort,
    order: params.order,
    page: params.page,
    pageSize: params.pageSize,
    assets: params.assets?.join(','),
    curators: params.curators?.join(','),
    zone: params.zone,
    keyword: params.keyword,
  });

  return {
    status: 'ok',
    chain,
    data: result,  // pagination + vault[] with address/asset/TVL/APY/curator
  };
}

// ───── getHoldings — User position snapshot across vaults + markets ─────
//
// [FILLED v0.1.3] Returns vault positions + market positions. Market
// positions carry isSmartLending / isFixedTerm / isActionable flags
// (computed upstream from zone/termType). Caller is responsible for the
// health label mapping (Healthy/Warning/Risk) per the SKILL.md guidelines.
async function getHoldings(params: {
  address: string;                              // wallet address to query
  chain?: string;
  scope?: 'all' | 'vault' | 'market' | 'selected';
}) {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, caip2: chainId } = chainResult;
  const scope = params.scope ?? 'all';

  if (!params.address) {
    return {
      status: 'error' as const,
      error_code: 'MISSING_ADDRESS',
      message: '`address` is required (the wallet whose holdings you want to query).',
    };
  }

  // Runtime hint:
  //   node ~/.claude/skills/lista-lending/dist/cli/cli.bundle.mjs holdings \
  //     --address <address> --chain <chainId> --scope <scope>
  // Output shape (matches upstream):
  //   { vaultPositions: [{vault, chain, deposited, depositedUsd, apy, walletBalance}, ...],
  //     marketPositions: [{market, chain, collateralUsd, borrowedUsd, ltv, health,
  //                        zone, termType, isSmartLending, isFixedTerm, isActionable}, ...],
  //     summary: { totalVaults, totalMarkets, actionableMarkets, unsupportedMarkets } }
  const result = await listaCli.run('holdings', {
    address: params.address,
    chain: chainId,
    scope,
  });

  return {
    status: 'ok',
    chain,
    scope,
    note:
      'Lista API indexer may lag 30-60s behind on-chain state. ' +
      'For real-time vault position state immediately after a deposit/withdraw, ' +
      'use getVaultPosition({vaultAddress, walletAddress}) instead.',
    data: result,
  };
}

// ───── getVaultPosition — Real-time on-chain vault position (no indexer) ─────
//
// [ADDED v0.1.6] Bypasses the Lista API indexer by reading ERC-4626 share
// balance + underlying value directly from the vault contract via RPC.
// Use immediately after a deposit/withdraw when getHoldings hasn't caught up,
// or when you want guaranteed fresh state.
//
// Required params: { vaultAddress, walletAddress }
// Optional params: { chain }  // 'bsc' (default) or 'ethereum'
async function getVaultPosition(params: {
  vaultAddress: string;
  walletAddress: string;
  chain?: string;
}) {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, id: chainId } = chainResult;
  const { vaultAddress, walletAddress } = params;

  const targetError =
    validateEvmAddress(vaultAddress, 'vaultAddress') ??
    validateEvmAddress(walletAddress, 'walletAddress');
  if (targetError) return targetError;

  // Read shares + symbol + underlying value (3 parallel RPC calls).
  const [shares, symbol, vaultInfo] = await Promise.all([
    erc4626.balanceOf(vaultAddress, walletAddress, chainId),
    erc4626.symbol(vaultAddress, chainId),
    listaSdk.getVaultInfo(chainId, vaultAddress),
  ]);
  const assetDecimals = (vaultInfo as any).assetInfo.decimals;
  const assetSymbol = (vaultInfo as any).assetInfo.symbol;
  const underlying = shares > 0n
    ? await erc4626.convertToAssets(vaultAddress, shares, chainId)
    : 0n;

  return {
    status: 'ok',
    chain,
    data: {
      vaultAddress,
      walletAddress,
      shares: {
        raw: shares.toString(),
        formatted: formatUnits(shares, assetDecimals),
        symbol,
      },
      underlying: {
        raw: underlying.toString(),
        formatted: formatUnits(underlying, assetDecimals),
        symbol: assetSymbol,
      },
      hasPosition: shares > 0n,
    },
  };
}

// ───── simulateBorrow — Dry-run borrow capacity check (no signature) ─────
//
// [ADDED + FILLED v0.1.3] Wraps Lista's existing buildBorrowSimulationPayload —
// returns projected loanable, safe borrow cap (95% of loanable), and
// optionally the after-supply loanable if `simulateSupply` is provided.
// Use before calling buildBorrow to surface capacity to the user.
async function simulateBorrow(params: {
  marketId: string;
  walletAddress: string;
  chain?: string;
  simulateSupply?: string;  // optional hypothetical supply amount in UI units
}) {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, caip2: chainId } = chainResult;

  // Runtime hint:
  //   node ~/.claude/skills/lista-lending/dist/cli/cli.bundle.mjs borrow --simulate \
  //     --market <marketId> --chain <chainId> --wallet-address <walletAddress> \
  //     [--simulate-supply <amount>]
  // Output (matches upstream buildBorrowSimulationPayload):
  //   { status, action: 'simulate', market, chain,
  //     collateral: {symbol, ...}, loan: {symbol, ...},
  //     current: { loanable, safeBorrow },
  //     afterSupply?: { loanable, safeBorrow, supplyAmount } }
  const result = await listaCli.run('borrow', {
    simulate: true,
    market: params.marketId,
    chain: chainId,
    walletAddress: params.walletAddress,
    simulateSupply: params.simulateSupply,
  });

  return {
    status: 'ok',
    chain,
    data: result,
  };
}

// ───── simulateRepay — Dry-run repay impact check (no signature) ─────
//
// [ADDED + FILLED v0.1.3] Wraps Lista's existing buildRepaySimulationPayload —
// returns the projected position after repay (new health factor, debt
// remaining). Use before calling buildRepay to confirm impact.
async function simulateRepay(params: {
  marketId: string;
  walletAddress: string;
  amount?: string;
  repayAll?: boolean;
  chain?: string;
}) {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain, caip2: chainId } = chainResult;

  if (!params.amount && !params.repayAll) {
    return {
      status: 'error' as const,
      error_code: 'MISSING_AMOUNT',
      message: 'Either `amount` or `repayAll: true` must be provided.',
    };
  }

  // Runtime hint:
  //   node ~/.claude/skills/lista-lending/dist/cli/cli.bundle.mjs repay --simulate \
  //     --market <marketId> --chain <chainId> --wallet-address <walletAddress> \
  //     (--amount <amount> | --repay-all)
  // Output (matches upstream buildRepaySimulationPayload):
  //   { status, action: 'simulate', market, chain,
  //     currentDebt, estimatedRepay, afterRepay: { debt, health, ... } }
  const result = await listaCli.run('repay', {
    simulate: true,
    market: params.marketId,
    chain: chainId,
    walletAddress: params.walletAddress,
    amount: params.amount,
    repayAll: params.repayAll,
  });

  return {
    status: 'ok',
    chain,
    data: result,
  };
}

// ============================================================================
// Public exports — every tool reachable by the Agent must be here
// ============================================================================
export {
  // Transaction tools (return pending_sign | ToolError)
  buildDeposit,
  buildWithdraw,
  buildSupply,
  buildBorrow,
  buildRepay,
  buildMarketWithdraw,
  // Read-only tools (return raw JSON; never trigger signing)
  listMarkets,
  listVaults,
  getHoldings,
  getVaultPosition,
  simulateBorrow,
  simulateRepay,
};
