[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "optimizer-calc"
version = "1.0.0"
description = "Polymarket Arbitrage Calculator"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.25.1",
]

[project.scripts]
optimizer-calc = "src.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
