// morpho-cli-onchainos — Onchain OS DApp Skill
// Generated by dapp-connect-agenticwallet v1.5 (Form B-REST equivalent — Morpho CLI as backend).
//
// RUNTIME MODEL — read carefully
//
// Two execution paths are supported:
//
// 1) LLM-simulated (default fallback): the LLM reads this file → "simulates" the function
//    body during inference (using Bash to call `npx @morpho-org/cli@latest`) → assembles
//    return JSON per pending_sign contract → routes to Onchain OS via next_action.tool.
//
// 2) Node-executed (preferred when package.json is present): `tsx cli.ts <toolName> '<json>'`
//    actually invokes the function from runtime.ts and prints the result. This is the model
//    used by automated tests (explore-plugin / test-skill) and CI smoke checks.
//
// Either way: keep functions as "pure functional calldata construction"; no local signing.

import {
  invokeMorphoCli,
  lc,
  type ToolError,
  type PreparedOperation,
} from './runtime.ts';

// ── pending_sign contract ────────────────────────────────────────────────────

type PendingSign = {
  status: 'pending_sign';
  unsigned_tx: {
    to: string;
    data: string;
    value: string;
    chain: string;
  };
  description: string;
  next_action: { tool: string; reason?: string };
  step_info?: { current: number; total: number; name?: string };
};

type OkRead<T = unknown> = { status: 'ok'; chain?: string; data: T };

// EIP-712 precision helper — injected unconditionally per scaffold rules.
// Morpho CLI tools don't currently emit EIP-712 signatures, but the helper
// is here so any future sign-message tools added to this skill use it from
// day one. (See SKILL.md template § "EIP-712 precision rule.")
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function toSafeInt(v: unknown): string {
  if (v === null || v === undefined) {
    throw new Error('[EIP712-PRECISION] field is null/undefined — check API response');
  }
  return BigInt(String(v)).toString();
}

// ── Chain resolver ───────────────────────────────────────────────────────────
// Source skill supports 11 chains. The chain id is informational here — the
// pending_sign envelope's `chain` field uses the slug, which is what onchainos
// `wallet contract-call --chain <slug>` expects.

const CHAINS: Record<string, { id: number }> = {
  ethereum:   { id: 1 },
  base:       { id: 8453 },
  arbitrum:   { id: 42161 },
  optimism:   { id: 10 },
  polygon:    { id: 137 },
  unichain:   { id: 130 },
  worldchain: { id: 480 },
  katana:     { id: 747474 },
  hyperevm:   { id: 999 },
  monad:      { id: 143 },
  stable:     { id: 20180427 },
};

function resolveChain(name: string | undefined): { name: string; id: number } | ToolError {
  const normalized = (name ?? 'base').toLowerCase();
  const entry = CHAINS[normalized];
  if (!entry) {
    return {
      status: 'error',
      error_code: 'UNSUPPORTED_CHAIN',
      message: `Chain '${name}' is not supported by this skill.`,
      suggestion: `Use one of: ${Object.keys(CHAINS).join(', ')}.`,
    };
  }
  return { name: normalized, ...entry };
}

// ── Validators ───────────────────────────────────────────────────────────────

function validatePositiveAmount(
  amount: string | undefined,
  fieldName = 'amount',
  opts: { allowMax?: boolean } = {},
): ToolError | null {
  if (amount === undefined || amount === null || amount === '') {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (amount === 'max') {
    if (opts.allowMax) return null;
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` does not accept 'max' on this operation. The 'max' keyword is only supported on prepareWithdraw, prepareRepay, and prepareWithdrawCollateral.`,
      suggestion: 'Provide a numeric amount (human-readable, e.g. "1000").',
    };
  }
  if (!/^\d+(\.\d+)?$/.test(amount)) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be a non-negative decimal string${opts.allowMax ? " or 'max'" : ''} (got '${amount}').`,
    };
  }
  if (Number(amount) === 0) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be greater than zero.`,
    };
  }
  return null;
}

function validateEvmAddress(addr: string | undefined, fieldName: string): ToolError | null {
  if (!addr) {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (!/^0x[a-fA-F0-9]{40}$/.test(addr)) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be a 0x-prefixed 40-char hex EVM address (got '${addr}').`,
    };
  }
  return null;
}

function validate32ByteHash(id: string | undefined, fieldName: string): ToolError | null {
  if (!id) {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (!/^0x[a-fA-F0-9]{64}$/.test(id)) {
    return {
      status: 'error',
      error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be a 0x-prefixed 64-char hex hash (got '${id}').`,
    };
  }
  return null;
}

// ── PreparedOperation → pending_sign reshape ─────────────────────────────────
// Morpho CLI's prepare-* commands return an array of unsigned transactions
// (approve + action). pending_sign carries one at a time. We emit the FIRST
// remaining transaction; after it lands, the agent re-invokes the same tool
// with the same params and the CLI re-prepares with the new on-chain state,
// dropping the approve if no longer needed. Idempotent + self-healing.

function preparedToPendingSign(
  prepared: PreparedOperation,
  toolName: string,
  chainSlug: string,
): PendingSign | ToolError {
  if (prepared.simulated && prepared.simulationOk === false) {
    return {
      status: 'error',
      error_code: 'SIMULATION_REVERTED',
      message: `Morpho simulation reverted: ${prepared.revertReason ?? 'unknown reason'}.`,
      suggestion: 'Inspect the revert reason. Common causes: insufficient allowance, ERC4626ExceededMaxWithdraw, insufficient balance.',
      details: { warnings: prepared.warnings, summary: prepared.summary },
    };
  }
  const liquidityShortfall = (prepared.warnings ?? []).find((w) =>
    /liquidity|withdraw|insufficient/i.test(w.message ?? ''),
  );
  if (liquidityShortfall && prepared.operation === 'withdraw') {
    // Don't block — partial withdrawals are valid by design. Just attach the warning
    // to the description so the agent surfaces it to the user.
  }

  if (!prepared.transactions || prepared.transactions.length === 0) {
    return {
      status: 'error',
      error_code: 'SDK_ERROR',
      message: `Morpho CLI returned a ${prepared.operation} prepared op with no transactions.`,
    };
  }

  const next = prepared.transactions[0];
  const total = prepared.transactions.length;
  const stepName =
    total > 1
      ? next.description?.toLowerCase().includes('approve')
        ? 'approve'
        : prepared.operation
      : prepared.operation;

  const reInvokeNote =
    total > 1
      ? ` After this transaction lands, re-invoke \`${toolName}\` with the same params to receive the next transaction.`
      : '';

  const warningsText =
    (prepared.warnings ?? []).length > 0
      ? ' Warnings: ' + (prepared.warnings ?? []).map((w) => w.message).join('; ')
      : '';

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: next.to,
      data: next.data,
      value: next.value ?? '0',
      chain: chainSlug,
    },
    description: `${prepared.summary}.${reInvokeNote}${warningsText}`,
    next_action: { tool: 'onchainos wallet contract-call' },
    step_info: total > 1 ? { current: 1, total, name: stepName } : undefined,
  };
}

// Wrap thrown ToolError (from runtime.ts) into a return value.
function safe<T>(fn: () => T): T | ToolError {
  try {
    return fn();
  } catch (e) {
    if (e && typeof e === 'object' && 'status' in e && (e as { status: unknown }).status === 'error') {
      return e as ToolError;
    }
    return {
      status: 'error',
      error_code: 'SDK_ERROR',
      message: (e as Error).message ?? String(e),
    };
  }
}

// =============================================================================
//   READ-ONLY TOOLS
// =============================================================================

export async function healthCheck(_params: Record<string, unknown> = {}): Promise<OkRead | ToolError> {
  return safe(() => {
    const data = invokeMorphoCli('health-check', {});
    return { status: 'ok' as const, data };
  });
}

export async function getSupportedChains(_params: Record<string, unknown> = {}): Promise<OkRead | ToolError> {
  return safe(() => {
    const data = invokeMorphoCli('get-supported-chains', {});
    return { status: 'ok' as const, data };
  });
}

export async function queryVaults(params: {
  chain?: string;
  assetSymbol?: string;
  assetAddress?: string;
  sort?: 'apy_desc' | 'apy_asc' | 'tvl_desc' | 'tvl_asc';
  limit?: number;
  skip?: number;
  fields?: string;
}): Promise<OkRead | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  if (params.assetAddress) {
    const err = validateEvmAddress(params.assetAddress, 'assetAddress');
    if (err) return err;
  }
  return safe(() => {
    const data = invokeMorphoCli('query-vaults', {
      chain: chainResult.name,
      'asset-symbol': params.assetSymbol,
      'asset-address': params.assetAddress ? lc(params.assetAddress) : undefined,
      sort: params.sort,
      limit: params.limit !== undefined ? String(params.limit) : undefined,
      skip: params.skip !== undefined ? String(params.skip) : undefined,
      fields: params.fields,
    });
    return { status: 'ok' as const, chain: chainResult.name, data };
  });
}

export async function getVault(params: {
  chain?: string;
  address: string;
}): Promise<OkRead | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const addrErr = validateEvmAddress(params.address, 'address');
  if (addrErr) return addrErr;
  return safe(() => {
    const data = invokeMorphoCli('get-vault', {
      chain: chainResult.name,
      address: lc(params.address),
    });
    return { status: 'ok' as const, chain: chainResult.name, data };
  });
}

export async function queryMarkets(params: {
  chain?: string;
  loanAsset?: string;
  collateralAsset?: string;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
  limit?: number;
  skip?: number;
  fields?: string;
}): Promise<OkRead | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  if (params.loanAsset) {
    const err = validateEvmAddress(params.loanAsset, 'loanAsset');
    if (err) return err;
  }
  if (params.collateralAsset) {
    const err = validateEvmAddress(params.collateralAsset, 'collateralAsset');
    if (err) return err;
  }
  return safe(() => {
    const data = invokeMorphoCli('query-markets', {
      chain: chainResult.name,
      'loan-asset': params.loanAsset ? lc(params.loanAsset) : undefined,
      'collateral-asset': params.collateralAsset ? lc(params.collateralAsset) : undefined,
      'sort-by': params.sortBy,
      'sort-direction': params.sortDirection,
      limit: params.limit !== undefined ? String(params.limit) : undefined,
      skip: params.skip !== undefined ? String(params.skip) : undefined,
      fields: params.fields,
    });
    return { status: 'ok' as const, chain: chainResult.name, data };
  });
}

export async function getMarket(params: {
  chain?: string;
  id: string;
}): Promise<OkRead | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const idErr = validate32ByteHash(params.id, 'id');
  if (idErr) return idErr;
  return safe(() => {
    const data = invokeMorphoCli('get-market', {
      chain: chainResult.name,
      id: params.id.toLowerCase(),
    });
    return { status: 'ok' as const, chain: chainResult.name, data };
  });
}

export async function getPositions(params: {
  chain?: string;
  userAddress: string;
}): Promise<OkRead | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const addrErr = validateEvmAddress(params.userAddress, 'userAddress');
  if (addrErr) return addrErr;
  return safe(() => {
    const data = invokeMorphoCli('get-positions', {
      chain: chainResult.name,
      'user-address': lc(params.userAddress),
    });
    return { status: 'ok' as const, chain: chainResult.name, data };
  });
}

export async function getTokenBalance(params: {
  chain?: string;
  userAddress: string;
  tokenAddress: string;
}): Promise<OkRead | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const userErr = validateEvmAddress(params.userAddress, 'userAddress');
  if (userErr) return userErr;
  const tokenErr = validateEvmAddress(params.tokenAddress, 'tokenAddress');
  if (tokenErr) return tokenErr;
  return safe(() => {
    const data = invokeMorphoCli('get-token-balance', {
      chain: chainResult.name,
      'user-address': lc(params.userAddress),
      'token-address': lc(params.tokenAddress),
    });
    return { status: 'ok' as const, chain: chainResult.name, data };
  });
}

export async function simulateTransactions(params: {
  chain?: string;
  from: string;
  transactions: Array<{ to: string; data: string; value?: string }> | string;
  analysisContext?: unknown;
}): Promise<OkRead | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const fromErr = validateEvmAddress(params.from, 'from');
  if (fromErr) return fromErr;
  if (params.transactions === undefined || params.transactions === null) {
    return { status: 'error', error_code: 'MISSING_PARAM', message: '`transactions` is required.' };
  }
  const txJson =
    typeof params.transactions === 'string' ? params.transactions : JSON.stringify(params.transactions);
  const ctxJson =
    params.analysisContext === undefined
      ? undefined
      : typeof params.analysisContext === 'string'
        ? (params.analysisContext as string)
        : JSON.stringify(params.analysisContext);
  return safe(() => {
    const data = invokeMorphoCli('simulate-transactions', {
      chain: chainResult.name,
      from: lc(params.from),
      transactions: txJson,
      'analysis-context': ctxJson,
    });
    return { status: 'ok' as const, chain: chainResult.name, data };
  });
}

// =============================================================================
//   WRITE TOOLS — return pending_sign
// =============================================================================

export async function prepareDeposit(params: {
  chain?: string;
  vaultAddress: string;
  userAddress: string;
  amount: string;
  noSimulate?: boolean;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const err =
    validateEvmAddress(params.vaultAddress, 'vaultAddress') ??
    validateEvmAddress(params.userAddress, 'userAddress') ??
    validatePositiveAmount(params.amount, 'amount');
  if (err) return err;
  const prepResult = safe(() =>
    invokeMorphoCli<PreparedOperation>('prepare-deposit', {
      chain: chainResult.name,
      'vault-address': lc(params.vaultAddress),
      'user-address': lc(params.userAddress),
      amount: params.amount,
      ...(params.noSimulate ? { 'no-simulate': '' } : {}),
    }),
  );
  if (typeof prepResult === 'object' && prepResult !== null && 'status' in prepResult && prepResult.status === 'error') {
    return prepResult as ToolError;
  }
  return preparedToPendingSign(prepResult as PreparedOperation, 'prepareDeposit', chainResult.name);
}

export async function prepareWithdraw(params: {
  chain?: string;
  vaultAddress: string;
  userAddress: string;
  amount: string;
  noSimulate?: boolean;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const err =
    validateEvmAddress(params.vaultAddress, 'vaultAddress') ??
    validateEvmAddress(params.userAddress, 'userAddress') ??
    validatePositiveAmount(params.amount, 'amount', { allowMax: true });
  if (err) return err;
  const prepResult = safe(() =>
    invokeMorphoCli<PreparedOperation>('prepare-withdraw', {
      chain: chainResult.name,
      'vault-address': lc(params.vaultAddress),
      'user-address': lc(params.userAddress),
      amount: params.amount,
      ...(params.noSimulate ? { 'no-simulate': '' } : {}),
    }),
  );
  if (typeof prepResult === 'object' && prepResult !== null && 'status' in prepResult && prepResult.status === 'error') {
    return prepResult as ToolError;
  }
  return preparedToPendingSign(prepResult as PreparedOperation, 'prepareWithdraw', chainResult.name);
}

export async function prepareSupply(params: {
  chain?: string;
  marketId: string;
  userAddress: string;
  amount: string;
  noSimulate?: boolean;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const err =
    validate32ByteHash(params.marketId, 'marketId') ??
    validateEvmAddress(params.userAddress, 'userAddress') ??
    validatePositiveAmount(params.amount, 'amount');
  if (err) return err;
  const prepResult = safe(() =>
    invokeMorphoCli<PreparedOperation>('prepare-supply', {
      chain: chainResult.name,
      'market-id': params.marketId.toLowerCase(),
      'user-address': lc(params.userAddress),
      amount: params.amount,
      ...(params.noSimulate ? { 'no-simulate': '' } : {}),
    }),
  );
  if (typeof prepResult === 'object' && prepResult !== null && 'status' in prepResult && prepResult.status === 'error') {
    return prepResult as ToolError;
  }
  return preparedToPendingSign(prepResult as PreparedOperation, 'prepareSupply', chainResult.name);
}

export async function prepareBorrow(params: {
  chain?: string;
  marketId: string;
  userAddress: string;
  borrowAmount: string;
  noSimulate?: boolean;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const err =
    validate32ByteHash(params.marketId, 'marketId') ??
    validateEvmAddress(params.userAddress, 'userAddress') ??
    validatePositiveAmount(params.borrowAmount, 'borrowAmount');
  if (err) return err;
  const prepResult = safe(() =>
    invokeMorphoCli<PreparedOperation>('prepare-borrow', {
      chain: chainResult.name,
      'market-id': params.marketId.toLowerCase(),
      'user-address': lc(params.userAddress),
      'borrow-amount': params.borrowAmount,
      ...(params.noSimulate ? { 'no-simulate': '' } : {}),
    }),
  );
  if (typeof prepResult === 'object' && prepResult !== null && 'status' in prepResult && prepResult.status === 'error') {
    return prepResult as ToolError;
  }
  const prepared = prepResult as PreparedOperation;
  const market = (prepared.outcome?.market ?? {}) as { healthFactor?: string; isHealthy?: boolean };
  if (market.healthFactor !== undefined) {
    const hf = Number(market.healthFactor);
    if (!Number.isNaN(hf) && hf < 1.0) {
      return {
        status: 'error',
        error_code: 'HEALTH_FACTOR_TOO_LOW',
        message: `Borrow would drop health factor to ${market.healthFactor} (< 1.0 is liquidatable).`,
        suggestion: 'Reduce the borrow amount or supply more collateral first.',
        details: { simulationSummary: prepared.summary },
      };
    }
  }
  return preparedToPendingSign(prepared, 'prepareBorrow', chainResult.name);
}

export async function prepareRepay(params: {
  chain?: string;
  marketId: string;
  userAddress: string;
  amount: string;
  noSimulate?: boolean;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const err =
    validate32ByteHash(params.marketId, 'marketId') ??
    validateEvmAddress(params.userAddress, 'userAddress') ??
    validatePositiveAmount(params.amount, 'amount', { allowMax: true });
  if (err) return err;
  const prepResult = safe(() =>
    invokeMorphoCli<PreparedOperation>('prepare-repay', {
      chain: chainResult.name,
      'market-id': params.marketId.toLowerCase(),
      'user-address': lc(params.userAddress),
      amount: params.amount,
      ...(params.noSimulate ? { 'no-simulate': '' } : {}),
    }),
  );
  if (typeof prepResult === 'object' && prepResult !== null && 'status' in prepResult && prepResult.status === 'error') {
    return prepResult as ToolError;
  }
  return preparedToPendingSign(prepResult as PreparedOperation, 'prepareRepay', chainResult.name);
}

export async function prepareSupplyCollateral(params: {
  chain?: string;
  marketId: string;
  userAddress: string;
  amount: string;
  noSimulate?: boolean;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const err =
    validate32ByteHash(params.marketId, 'marketId') ??
    validateEvmAddress(params.userAddress, 'userAddress') ??
    validatePositiveAmount(params.amount, 'amount');
  if (err) return err;
  const prepResult = safe(() =>
    invokeMorphoCli<PreparedOperation>('prepare-supply-collateral', {
      chain: chainResult.name,
      'market-id': params.marketId.toLowerCase(),
      'user-address': lc(params.userAddress),
      amount: params.amount,
      ...(params.noSimulate ? { 'no-simulate': '' } : {}),
    }),
  );
  if (typeof prepResult === 'object' && prepResult !== null && 'status' in prepResult && prepResult.status === 'error') {
    return prepResult as ToolError;
  }
  return preparedToPendingSign(prepResult as PreparedOperation, 'prepareSupplyCollateral', chainResult.name);
}

export async function prepareWithdrawCollateral(params: {
  chain?: string;
  marketId: string;
  userAddress: string;
  amount: string;
  noSimulate?: boolean;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const err =
    validate32ByteHash(params.marketId, 'marketId') ??
    validateEvmAddress(params.userAddress, 'userAddress') ??
    validatePositiveAmount(params.amount, 'amount', { allowMax: true });
  if (err) return err;
  const prepResult = safe(() =>
    invokeMorphoCli<PreparedOperation>('prepare-withdraw-collateral', {
      chain: chainResult.name,
      'market-id': params.marketId.toLowerCase(),
      'user-address': lc(params.userAddress),
      amount: params.amount,
      ...(params.noSimulate ? { 'no-simulate': '' } : {}),
    }),
  );
  if (typeof prepResult === 'object' && prepResult !== null && 'status' in prepResult && prepResult.status === 'error') {
    return prepResult as ToolError;
  }
  const prepared = prepResult as PreparedOperation;
  const market = (prepared.outcome?.market ?? {}) as { healthFactor?: string; isHealthy?: boolean };
  if (market.healthFactor !== undefined) {
    const hf = Number(market.healthFactor);
    if (!Number.isNaN(hf) && hf < 1.0) {
      return {
        status: 'error',
        error_code: 'HEALTH_FACTOR_TOO_LOW',
        message: `Collateral withdrawal would drop health factor to ${market.healthFactor} (< 1.0 is liquidatable).`,
        suggestion: 'Reduce the withdrawal amount or repay debt first.',
        details: { simulationSummary: prepared.summary },
      };
    }
  }
  return preparedToPendingSign(prepared, 'prepareWithdrawCollateral', chainResult.name);
}
