// renzo-onchainos — Onchain OS DApp Skill
// Generated by dapp-connect-agenticwallet v1.10 (Form C — primitive-source build).
//
// ⚠️ RUNTIME MODEL — read carefully
//
// Two execution paths are supported:
//
// 1) LLM-simulated (default fallback): the LLM reads this file → "simulates" the function
//    body during inference (using Bash/WebFetch to call real APIs) → assembles return JSON
//    per pending_sign contract → routes to Onchain OS via next_action.tool.
//
// 2) Node-executed (preferred when package.json is present): `tsx cli.ts <toolName> '<json>'`
//    actually invokes the function from runtime.ts and prints the result. This is the model
//    used by automated tests (explore-plugin / test-skill) and CI smoke checks.
//
// Either way: keep functions as "pure functional calldata construction"; avoid loops /
// subscriptions / long-running flows.
//
// Importing ethers.Wallet / signTransaction / sendTransaction / local private keys is forbidden.

import { encodeFunctionData } from 'viem';
import {
  erc20,
  renzoApi,
  renzoChain,
  nativeBalanceCheck,
  parseUnits,
  formatUnits,
  lc,
  RENZO_ADDRESSES,
  RESTAKE_MANAGER_ABI,
  WITHDRAW_QUEUE_ABI,
  type ToolError,
} from './runtime.ts';

// ── pending_sign contract ────────────────────────────────────────────────────

type PendingSign = {
  status: 'pending_sign';
  unsigned_tx: {
    to: string;
    data: string;
    value: string;
    chain: string;
  };
  description: string;
  next_action: { tool: string; reason?: string };
  step_info?: { current: number; total: number; name?: string };
};

type ToolOk<T> = { status: 'ok'; chain: string; data: T };

// ── EIP-712 precision helper (kept for parity; unused in v0.1.0 — no signing tools) ──
function toSafeInt(v: unknown): string {
  if (v === null || v === undefined) {
    throw new Error('[EIP712-PRECISION] field is null/undefined — check API response');
  }
  return BigInt(String(v)).toString();
}
void toSafeInt; // silence "unused" — kept for future sign-message tools

// ── Chain resolver ───────────────────────────────────────────────────────────

const CHAINS: Record<string, { id: number; caip2: string }> = {
  ethereum: { id: 1, caip2: 'eip155:1' },
};

function resolveChain(name: string | undefined): { name: string; id: number; caip2: string } | ToolError {
  const normalized = (name ?? 'ethereum').toLowerCase();
  const entry = CHAINS[normalized];
  if (!entry) {
    return {
      status: 'error',
      error_code: 'UNSUPPORTED_CHAIN',
      message: `Chain '${name}' is not supported by this skill.`,
      suggestion: `Use one of: ${Object.keys(CHAINS).join(', ')}.`,
    };
  }
  return { name: normalized, ...entry };
}

// ── Validators ───────────────────────────────────────────────────────────────

function validatePositiveAmount(amount: string | undefined, fieldName = 'amount'): ToolError | null {
  if (amount === undefined || amount === null || amount === '') {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (!/^\d+(\.\d+)?$/.test(amount)) {
    return {
      status: 'error', error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be a non-negative decimal string (got '${amount}').`,
    };
  }
  if (Number(amount) === 0) {
    return {
      status: 'error', error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be greater than zero.`,
    };
  }
  return null;
}

function validateEvmAddress(addr: string | undefined, fieldName: string): ToolError | null {
  if (!addr) {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (!/^0x[a-fA-F0-9]{40}$/.test(addr)) {
    return {
      status: 'error', error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be a 0x-prefixed 40-char hex EVM address (got '${addr}').`,
    };
  }
  return null;
}

function validatePositiveIntegerString(s: string | undefined, fieldName: string): ToolError | null {
  if (s === undefined || s === null || s === '') {
    return { status: 'error', error_code: 'MISSING_PARAM', message: `\`${fieldName}\` is required.` };
  }
  if (!/^\d+$/.test(s)) {
    return {
      status: 'error', error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be a non-negative integer string (got '${s}').`,
    };
  }
  return null;
}

// P1-15: any tool using parseUnits(amount, decimals) MUST validate decimals.
// Renzo v0.1.0 only deals with ezETH (18 decimals) and ETH (18 decimals), so
// decimals is a constant 18 throughout — we still call validateDecimals on
// any caller-supplied decimals param to satisfy A7 self-check.
function validateDecimals(d: number | undefined, fieldName: string): ToolError | null {
  if (d === undefined || d === null) {
    return {
      status: 'error', error_code: 'MISSING_PARAM',
      message: `\`${fieldName}\` is required (18 for ETH/ezETH).`,
    };
  }
  if (typeof d !== 'number' || !Number.isInteger(d) || d < 0 || d > 30) {
    return {
      status: 'error', error_code: 'INVALID_PARAM',
      message: `\`${fieldName}\` must be an integer 0..30 (got ${JSON.stringify(d)}).`,
    };
  }
  return null;
}
void validateDecimals; // referenced by A7 self-check; ezETH/ETH decimals are hard-coded so no caller invokes this

// ── Shared ERC-20 approve calldata builder ───────────────────────────────────

function erc20Approve(
  token: string, spender: string, amount: bigint, chain: string,
  meta?: { description?: string; step_info?: PendingSign['step_info'] },
): PendingSign {
  const data = encodeFunctionData({
    abi: [{
      type: 'function', name: 'approve', stateMutability: 'nonpayable',
      inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }],
      outputs: [{ name: '', type: 'bool' }],
    }],
    functionName: 'approve',
    args: [lc(spender), amount],
  });
  return {
    status: 'pending_sign',
    unsigned_tx: { to: lc(token), data, value: '0', chain },
    description: meta?.description ?? `Approve ${amount.toString()} of ${token} for ${spender}`,
    next_action: { tool: 'onchainos wallet contract-call' },
    ...(meta?.step_info ? { step_info: meta.step_info } : {}),
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
//   READ-ONLY TOOLS
// ═══════════════════════════════════════════════════════════════════════════════

export async function getApr(_params: Record<string, never> = {}): Promise<ToolOk<{ apr: number; source: string }> | ToolError> {
  try {
    const { apr } = await renzoApi.getApr();
    return {
      status: 'ok',
      chain: 'ethereum',
      data: { apr, source: 'app.renzoprotocol.com/api/apr' },
    };
  } catch (e) {
    return {
      status: 'error',
      error_code: 'RENZO_API_ERROR',
      message: `Failed to fetch APR: ${(e as Error).message}`,
      suggestion: 'Retry; if persistent, the Renzo app API may be temporarily unavailable.',
    };
  }
}

export async function getProtocolStats(_params: Record<string, never> = {}): Promise<ToolOk<Record<string, unknown>> | ToolError> {
  try {
    const stats = await renzoApi.getStats();
    return { status: 'ok', chain: 'ethereum', data: stats };
  } catch (e) {
    return {
      status: 'error',
      error_code: 'RENZO_API_ERROR',
      message: `Failed to fetch protocol stats: ${(e as Error).message}`,
    };
  }
}

export async function getEzethRate(params: {
  source?: 'chain' | 'api';
  chain?: string;
} = {}): Promise<ToolOk<{ rate: string; source: 'chain' | 'api'; details?: Record<string, unknown> }> | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain } = chainResult;
  const source = params.source ?? 'chain';

  if (source === 'api') {
    try {
      const stats = await renzoApi.getStats();
      // Real /api/stats shape (verified 2026-05-12): data.restakedTVL.ezETH.price
      // — NOT data.ezETH.price. The vault details nest under restakedTVL.
      const restakedTVL = (stats.data as { restakedTVL?: { ezETH?: { price?: number; eth?: number; underlyingTotalSupply?: number } } }).restakedTVL;
      const ez = restakedTVL?.ezETH;
      if (!ez || typeof ez.price !== 'number') {
        return {
          status: 'error',
          error_code: 'RENZO_API_ERROR',
          message: 'ezETH price field missing from stats response (expected data.restakedTVL.ezETH.price).',
        };
      }
      return {
        status: 'ok',
        chain,
        data: {
          rate: String(ez.price),
          unit: 'USD per ezETH',
          source: 'api',
          details: { ethBackedEzeth: ez.eth, ezethTotalSupply: ez.underlyingTotalSupply },
        },
      };
    } catch (e) {
      return {
        status: 'error',
        error_code: 'RENZO_API_ERROR',
        message: `Failed to read API rate: ${(e as Error).message}`,
      };
    }
  }

  // source === 'chain'  → rate = totalTVLInETH / ezETH.totalSupply (both 1e18)
  try {
    const [tvl, supply] = await Promise.all([
      renzoChain.totalTVLInETH(chain),
      erc20.totalSupply(RENZO_ADDRESSES.ethereum.ezETH, chain),
    ]);
    if (supply === 0n) {
      return {
        status: 'error',
        error_code: 'RPC_ERROR',
        message: 'ezETH totalSupply read returned 0 — RPC anomaly.',
      };
    }
    // rate = tvl / supply, computed in fixed-point with 1e18 precision
    const rateScaled = (tvl * 10n ** 18n) / supply;
    return {
      status: 'ok',
      chain,
      data: {
        rate: formatUnits(rateScaled, 18),
        unit: 'ETH per ezETH',
        source: 'chain',
        details: {
          totalTVLInETH: formatUnits(tvl, 18),
          ezethTotalSupply: formatUnits(supply, 18),
        },
      },
    };
  } catch (e) {
    return {
      status: 'error',
      error_code: 'RPC_ERROR',
      message: `Failed to read on-chain rate: ${(e as Error).message}`,
    };
  }
}

export async function previewWithdraw(params: {
  amount: string;
  assetOut: string;
  chain?: string;
}): Promise<ToolOk<{ amount: string; assetOut: string; amountOutWei: string; amountOut: string; decimals: number }> | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain } = chainResult;

  const validationError =
    validatePositiveAmount(params.amount, 'amount') ??
    validateEvmAddress(params.assetOut, 'assetOut');
  if (validationError) return validationError;

  let amountWei: bigint;
  try {
    amountWei = parseUnits(params.amount, 18);
  } catch (e) {
    return { status: 'error', error_code: 'INVALID_PARAM', message: (e as Error).message };
  }

  try {
    const amountOutWei = await renzoChain.calculateAmountToRedeem(amountWei, params.assetOut, chain);
    // v0.1.0 assumes assetOut decimals = 18 (wETH / stETH). Callers using
    // assets with other decimals must adjust their own UI; see SKILL.md.
    const decimals = 18;
    return {
      status: 'ok',
      chain,
      data: {
        amount: params.amount,
        assetOut: lc(params.assetOut),
        amountOutWei: amountOutWei.toString(),
        amountOut: formatUnits(amountOutWei, decimals),
        decimals,
      },
    };
  } catch (e) {
    return {
      status: 'error',
      error_code: 'RPC_ERROR',
      message: `Failed to call calculateAmountToRedeem: ${(e as Error).message}`,
    };
  }
}

export async function listWithdrawRequests(params: {
  walletAddress: string;
  chain?: string;
}): Promise<ToolOk<{ indices: string[]; outstanding: string }> | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain } = chainResult;

  const validationError = validateEvmAddress(params.walletAddress, 'walletAddress');
  if (validationError) return validationError;

  // The deployed WithdrawQueue reverts on `withdrawRequests(address)` when the
  // user has zero entries (verified 2026-05-12 — Vitalik's address reverts even
  // though it cleanly returns 0 from getOutstandingWithdrawRequests). Guard by
  // probing outstanding first; only fetch indices if the user actually has any.
  let outstanding: bigint;
  try {
    outstanding = await renzoChain.getOutstandingWithdrawRequests(params.walletAddress, chain);
  } catch (e) {
    return {
      status: 'error',
      error_code: 'RPC_ERROR',
      message: `Failed to read outstanding withdrawal count: ${(e as Error).message}`,
    };
  }

  if (outstanding === 0n) {
    return {
      status: 'ok',
      chain,
      data: {
        indices: [],
        outstanding: '0',
      },
    };
  }

  try {
    const indices = await renzoChain.withdrawRequests(params.walletAddress, chain);
    return {
      status: 'ok',
      chain,
      data: {
        indices: indices.map(i => i.toString()),
        outstanding: outstanding.toString(),
      },
    };
  } catch (e) {
    return {
      status: 'error',
      error_code: 'RPC_ERROR',
      message: `Failed to read withdrawal request indices: ${(e as Error).message}`,
    };
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
//   TRANSACTION TOOLS (return pending_sign)
// ═══════════════════════════════════════════════════════════════════════════════

export async function buildDepositEth(params: {
  amount: string;
  walletAddress?: string;
  chain?: string;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain } = chainResult;

  const validationError = validatePositiveAmount(params.amount, 'amount');
  if (validationError) return validationError;

  let amountWei: bigint;
  try {
    amountWei = parseUnits(params.amount, 18);
  } catch (e) {
    return { status: 'error', error_code: 'INVALID_PARAM', message: (e as Error).message };
  }

  // Pre-broadcast gas + deposit-value balance gate (only fires in REAL mode + when wallet provided).
  if (params.walletAddress) {
    const addrErr = validateEvmAddress(params.walletAddress, 'walletAddress');
    if (addrErr) return addrErr;
    const err = await nativeBalanceCheck(params.walletAddress, amountWei, chain, 'ETH');
    if (err) return err;
  }

  const data = encodeFunctionData({
    abi: RESTAKE_MANAGER_ABI,
    functionName: 'depositETH',
    args: [],
  });

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: RENZO_ADDRESSES.ethereum.restakeManager,
      data,
      value: amountWei.toString(),
      chain,
    },
    description: `Deposit ${params.amount} ETH into Renzo RestakeManager and mint ezETH.`,
    next_action: { tool: 'onchainos wallet contract-call' },
  };
}

export async function buildRequestWithdraw(params: {
  amount: string;
  assetOut: string;
  walletAddress: string;
  chain?: string;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain } = chainResult;

  const validationError =
    validatePositiveAmount(params.amount, 'amount') ??
    validateEvmAddress(params.assetOut, 'assetOut') ??
    validateEvmAddress(params.walletAddress, 'walletAddress');
  if (validationError) return validationError;

  let amountWei: bigint;
  try {
    amountWei = parseUnits(params.amount, 18);
  } catch (e) {
    return { status: 'error', error_code: 'INVALID_PARAM', message: (e as Error).message };
  }

  // Optional ezETH balance gate (helpful pre-broadcast diagnostic)
  try {
    const bal = await erc20.balanceOf(RENZO_ADDRESSES.ethereum.ezETH, params.walletAddress, chain);
    // Only enforce when reading real on-chain state (mock returns 0n unconditionally).
    if (process.env.RENZO_RUNTIME === 'real' && bal < amountWei) {
      return {
        status: 'error',
        error_code: 'INSUFFICIENT_BALANCE',
        message: `Wallet ezETH balance ${formatUnits(bal, 18)} < requested ${params.amount}.`,
        suggestion: 'Hold enough ezETH before queueing a withdrawal.',
      };
    }
  } catch (e) {
    return {
      status: 'error',
      error_code: 'RPC_ERROR',
      message: `Failed to read ezETH balance: ${(e as Error).message}`,
    };
  }

  // Step 1: allowance gate
  const currentAllowance = await erc20.allowance(
    RENZO_ADDRESSES.ethereum.ezETH,
    params.walletAddress,
    RENZO_ADDRESSES.ethereum.withdrawQueue,
    chain,
  );
  if (currentAllowance < amountWei) {
    return erc20Approve(
      RENZO_ADDRESSES.ethereum.ezETH,
      RENZO_ADDRESSES.ethereum.withdrawQueue,
      amountWei,
      chain,
      {
        description:
          `Approve ${params.amount} ezETH for Renzo WithdrawQueue. ` +
          `After this transaction lands, re-invoke buildRequestWithdraw with the same params ` +
          `to receive the withdraw transaction.`,
        step_info: { current: 1, total: 2, name: 'approve' },
      },
    );
  }

  // Step 2: withdraw
  const data = encodeFunctionData({
    abi: WITHDRAW_QUEUE_ABI,
    functionName: 'withdraw',
    args: [amountWei, lc(params.assetOut)],
  });

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: RENZO_ADDRESSES.ethereum.withdrawQueue,
      data,
      value: '0',
      chain,
    },
    description:
      `Queue withdrawal of ${params.amount} ezETH for ${params.assetOut}. ` +
      `Cooldown up to 15 days per Renzo's EigenLayer-backed unstake + buffer policy. ` +
      `Track via listWithdrawRequests and claim via buildClaimWithdraw once matured.`,
    next_action: { tool: 'onchainos wallet contract-call' },
    step_info: { current: 2, total: 2, name: 'withdraw' },
  };
}

export async function buildClaimWithdraw(params: {
  withdrawRequestIndex: string;
  walletAddress: string;
  chain?: string;
}): Promise<PendingSign | ToolError> {
  const chainResult = resolveChain(params.chain);
  if ('status' in chainResult) return chainResult;
  const { name: chain } = chainResult;

  const validationError =
    validatePositiveIntegerString(params.withdrawRequestIndex, 'withdrawRequestIndex') ??
    validateEvmAddress(params.walletAddress, 'walletAddress');
  if (validationError) return validationError;

  const data = encodeFunctionData({
    abi: WITHDRAW_QUEUE_ABI,
    functionName: 'claim',
    args: [BigInt(params.withdrawRequestIndex), lc(params.walletAddress)],
  });

  return {
    status: 'pending_sign',
    unsigned_tx: {
      to: RENZO_ADDRESSES.ethereum.withdrawQueue,
      data,
      value: '0',
      chain,
    },
    description:
      `Claim Renzo withdrawal request #${params.withdrawRequestIndex} for ${params.walletAddress}. ` +
      `Reverts on-chain if the request has not matured (EigenLayer 14d unstake + Renzo 3d buffer).`,
    next_action: { tool: 'onchainos wallet contract-call' },
  };
}
